version: '3'

services:
  node:
    build: .
    env_file: .env
    ports:
      - "81:3000"
    volumes:
      - ./app:/home/node/app
      - node_modules:/home/node/app/node_modules
  bd:
    image: mariadb:latest
    env_file: .env
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - dados_mariadb:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dados_mariadb:
  node_modules: